default_job = "toboggan"

[jobs.toboggan]
command = ["toboggan", "build", "-o", "rust-python.toml"]
need_stdout = true
allow_warnings = true
default_watch = false
watch = ["slides"]

[jobs.html]
command = ["toboggan", "build", "-o", "index.html"]
need_stdout = true
allow_warnings = true
default_watch = false
watch = ["slides"]
