// Generated by toboggan-cli — compile with: typst compile presentation.typ

#set page(
  paper: "presentation-16-9",
  margin: (x: 2cm, y: 1.5cm),
)
#set text(size: 20pt)
#set heading(numbering: none)
#show heading.where(level: 1): it => block(below: 0.8em)[
  #text(size: 28pt, weight: "bold")[#it.body]
]

// ── Cover ──────────────────────────────────────────────────────────────────
#align(center + horizon)[
  #text(size: 36pt, weight: "bold")[Crabe & Serpent : un mariage de raison]
  #v(1em)
  #text(size: 20pt, fill: luma(120))[2026-05-01]
]
#pagebreak()

// ── Section ───────────────────────────────────────────────────────────────
#align(center + horizon)[
  #text(size: 30pt, weight: "semibold")[1. Mise en bouche]
]
#pagebreak()

// ── Slide ────────────────────────────────────────────────────────────────
= Le constat
La stack Python qui va vite, aujourd'hui, est #strong[écrite en Rust].

- 🐼 #link("https://pola.rs/")[Polars] — DataFrame
- 🧹 #link("https://github.com/astral-sh/ruff")[Ruff] — linter
- 📦 #link("https://github.com/astral-sh/uv")[uv] — package manager
- ✅ #link("https://github.com/pydantic/pydantic-core")[Pydantic v2] — validation
- 🤗 #link("https://github.com/huggingface/tokenizers")[Tokenizers] — NLP
- ⚡ #link("https://github.com/ijl/orjson")[orjson] — JSON

#quote(block: true)[
Et ce n'est qu'un début…

]

#pagebreak()

// ── Slide ────────────────────────────────────────────────────────────────
= 🦀 Rust en bref
- #strong[Performances] : sans GC, proche du métal
- #strong[Sûreté mémoire] : ownership, borrow checker
- #strong[Système de types] : enums, traits, lifetimes
- #strong[Fearless concurrency] : data race = erreur de compilation
- #strong[Bas niveau, mais ergonomique]

#pagebreak()

// ── Slide ────────────────────────────────────────────────────────────────
= 🐍 Python en bref
- #strong[Souple, expressif, rapide à écrire]
- #strong[Itération rapide] : prototypage, exploration, REPL
- #strong[Accessibilité] : scolaire, scientifique, débutant
- #strong[Écosystème colossal] : data, ML, web, scripting
- #strong[Lent en pur Python] → libs natives pour la perf

#quote(block: true)[
NumPy, PyTorch, TensorFlow… déjà en C/C++. Et maintenant en Rust.

]

#pagebreak()

// ── Slide ────────────────────────────────────────────────────────────────
= Quand Rust rencontre Python
#table(
  columns: 2,
  [Rust apporte],
  [Python apporte],
  [Perf et sûreté],
  [Souplesse],
  [Concurrence],
  [Écosystème],
  [Système de types],
  [Accessibilité],
  [Bas niveau],
  [Prototypage],
)

#quote(block: true)[
#strong[Le meilleur des deux mondes ?]

]

#pagebreak()

// ── Section ───────────────────────────────────────────────────────────────
#align(center + horizon)[
  #text(size: 30pt, weight: "semibold")[2. Les fondations]
]
#pagebreak()

// ── Slide ────────────────────────────────────────────────────────────────
= ABI C, lingua franca
#strong[ABI] ≠ API

- #strong[A]pplication #strong[B]inary #strong[I]nterface
- Convention de bas niveau : registres, pile, layout mémoire

Presque tous les langages #strong[savent appeler C].

→ Si Rust expose une fonction `extern "C"`, Python (ou n'importe quel langage) peut l'appeler.

#pagebreak()

// ── Slide ────────────────────────────────────────────────────────────────
= Schéma d'un appel C
System V AMD64 (Linux/macOS) :

```text
   Caller                                 Callee
 ┌─────────────────────┐                ┌─────────────────────┐
 │ rdi, rsi, rdx,      │ ─ 6 args int ▶ │                     │
 │ rcx,  r8, r9        │                │  exécute            │
 │ xmm0..xmm7          │ ─ flottants ─▶ │                     │
 │ pile (au-delà)      │                │  rax = résultat     │
 │                     │ ─── call ───▶  │  ret                │
 │ rax ← retour        │ ◄── return ──  │                     │
 └─────────────────────┘                └─────────────────────┘
```

#strong[Frictions :]

- Name mangling (`extern "C"`)
- Layout (`repr(C)`)
- Strings : `\0` vs `(ptr, len)`

#pagebreak()

// ── Slide ────────────────────────────────────────────────────────────────
= Python : appeler du natif
```python
import ctypes
lib = ctypes.CDLL("./libmath.so")
lib.add.argtypes = [ctypes.c_int, ctypes.c_int]
lib.add.restype = ctypes.c_int
print(lib.add(2, 3))  # 5
```

#table(
  columns: 3,
  [Approche],
  [Pour],
  [Contre],
  [`ctypes`],
  [Pas de compilation],
  [Lent, peu sûr],
  [`cffi`],
  [Plus propre],
  [Dépendance],
  [#strong[C-API CPython]],
  [Perf max, intégration native],
  [C, tout à la main],
  [#strong[PyO3]],
  [Ergonomie + perf C-API],
  [Compile Rust],
)

#pagebreak()

// ── Slide ────────────────────────────────────────────────────────────────
= Rust : exposer du C
```rust
#[unsafe(no_mangle)]
pub extern "C" fn add(a: i32, b: i32) -> i32 {
    a + b
}

#[repr(C)]
pub struct Point {
    x: f64,
    y: f64,
}
```

```bash
$ cargo build --release
   → target/release/libmacrate.{so|dylib|dll}
```

#pagebreak()

// ── Slide ────────────────────────────────────────────────────────────────
= Le pont
```text
   Python                  ABI C                   Rust
 ┌──────────┐         ┌────────────┐         ┌─────────────┐
 │ PyObject │ ──────▶ │ extern "C" │ ──────▶ │ #[pyclass]  │
 │   .py    │ ◄────── │  no_mangle │ ◄────── │  Rust code  │
 └──────────┘         └────────────┘         └─────────────┘
                       PyO3 / Maturin
                       génèrent ce pont
```

→ #strong[Vous écrivez du Rust idiomatique.] → #strong[PyO3 + Maturin font tout le sale boulot.]

#pagebreak()

// ── Section ───────────────────────────────────────────────────────────────
#align(center + horizon)[
  #text(size: 30pt, weight: "semibold")[3. L'écosystème]
]
#pagebreak()

// ── Slide ────────────────────────────────────────────────────────────────
= 🦀 dans 🐍
Le Rust gagne du terrain comme #strong[moteur natif] :

- 📊 #link("https://pola.rs/")[Polars] — DataFrame
- 🧹 #link("https://github.com/astral-sh/ruff")[Ruff] — linter
- 📦 #link("https://github.com/astral-sh/uv")[uv] — package manager
- ✅ #link("https://github.com/pydantic/pydantic-core")[Pydantic v2] — validation
- 🤗 #link("https://github.com/huggingface/tokenizers")[Tokenizers] — NLP
- ⚡ #link("https://github.com/ijl/orjson")[orjson] — JSON
- 🧮 #link("https://github.com/apache/datafusion-python")[DataFusion] — SQL
- 🌐 #link("https://github.com/emmett-framework/granian")[Granian], #link("https://robyn.tech/")[Robyn] — serveurs HTTP

#pagebreak()

// ── Slide ────────────────────────────────────────────────────────────────
= 🐍 dans 🦀
L'inverse existe aussi :

- #strong[Scripting / plugins] : embarquer un interpréteur Python pour la config, l'extension
- #strong[ML/IA] : piloter PyTorch / scikit-learn depuis un service Rust
- #strong[Migration progressive] : remplacer brique par brique sans tout réécrire
- #strong[Outillage] : exposer du tooling Python (linters, formatters) à un binaire Rust

→ Moins courant, mais bien supporté par PyO3.

#pagebreak()

// ── Section ───────────────────────────────────────────────────────────────
#align(center + horizon)[
  #text(size: 30pt, weight: "semibold")[4. Du code, du vrai]
]
#pagebreak()

// ── Slide ────────────────────────────────────────────────────────────────
= La stack
== #link("https://pyo3.rs/")[PyO3] + #link("https://www.maturin.rs/")[Maturin]
- #strong[PyO3] : bindings Rust ↔ Python (les macros)
- #strong[Maturin] : build & packaging des wheels

```bash
$ maturin develop          # dev local
$ maturin build --release  # produit une wheel
```

#pagebreak()

// ── Slide ────────────────────────────────────────────────────────────────
= Setup minimal
```toml
# Cargo.toml
[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.28", features = ["abi3-py38"] }
```

```toml
# pyproject.toml
[build-system]
requires = ["maturin>=1.0"]
build-backend = "maturin"
```

→ C'est tout.

#pagebreak()

// ── Slide ────────────────────────────────────────────────────────────────
= Exemple 1 — Markdown via comrak
```rust
use pyo3::prelude::*;

#[pyfunction]
fn markdown_to_html(input: &str) -> String {
    comrak::markdown_to_html(input, &comrak::Options::default())
}

#[pymodule]
fn rusty_md(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(markdown_to_html, m)?)?;
    Ok(())
}
```

```python
from rusty_md import markdown_to_html
print(markdown_to_html("# Hello **world**"))
# <h1>Hello <strong>world</strong></h1>
```

#pagebreak()

// ── Slide ────────────────────────────────────────────────────────────────
= Exemple 2 — Stats sur logs
```rust
#[pyfunction]
fn stats(durations_ms: Vec<f64>) -> (f64, f64, f64, f64) {
    let n = durations_ms.len() as f64;
    let sum: f64 = durations_ms.iter().sum();
    let avg = sum / n;
    let min = durations_ms.iter().copied()
        .fold(f64::INFINITY, f64::min);
    let max = durations_ms.iter().copied()
        .fold(f64::NEG_INFINITY, f64::max);
    let var = durations_ms.iter()
        .map(|x| (x - avg).powi(2))
        .sum::<f64>() / n;
    (avg, min, max, var.sqrt())
}
```

#pagebreak()

// ── Slide ────────────────────────────────────────────────────────────────
= Bench Python vs Rust vs PyO3
```python
import statistics, timeit
from log_analyze import stats as rust_stats

def py_stats(xs):
    return (statistics.mean(xs), min(xs),
            max(xs), statistics.stdev(xs))

xs = [...]  # 1M de mesures
print("py:  ", timeit.timeit(lambda: py_stats(xs), number=10))
print("rust:", timeit.timeit(lambda: rust_stats(xs), number=10))
```

À mesurer :

- `Vec<f64>` (copie) vs `&PyList` (zero-copy)
- Lire le log en Rust vs en Python
- Coût FFI s'amortit sur le volume

#pagebreak()

// ── Slide ────────────────────────────────────────────────────────────────
= Exemple 3 — Python dans Rust
```rust
use pyo3::prelude::*;

fn main() -> PyResult<()> {
    Python::with_gil(|py| {
        let math = py.import("math")?;
        let pi: f64 = math.getattr("pi")?.extract()?;
        println!("π = {pi}");

        py.run(c"print('Hello from embedded Python')",
               None, None)?;
        Ok(())
    })
}
```

```toml
pyo3 = { version = "0.28", features = ["auto-initialize"] }
```

#pagebreak()

// ── Slide ────────────────────────────────────────────────────────────────
= Ce qu'on peut faire
- ✅ #strong[Modules] : `#[pymodule]`
- ✅ #strong[Fonctions] : `#[pyfunction]`
- ✅ #strong[Classes] : `#[pyclass]` + `#[pymethods]`
- ✅ #strong[Exceptions custom] : `create_exception!`
- ✅ #strong[Sous-modules], conversions auto
- ✅ #strong[NumPy] : crate #link("https://github.com/PyO3/rust-numpy")[`rust-numpy`]
- ✅ #strong[Async] : #link("https://github.com/PyO3/pyo3-async-runtimes")[`pyo3-async-runtimes`]
- ✅ #strong[Type stubs] (`.pyi`) pour l'IDE / mypy

#pagebreak()

// ── Slide ────────────────────────────────────────────────────────────────
= Ce qu'on ne peut pas (facilement)
```rust
// ❌ Génériques exposés tels quels
#[pyclass]
struct Container<T> { /* ... */ }   // ne compile pas
```

```rust
// ✅ Solution : monomorphiser
#[pyclass] struct IntContainer { /* ... */ }
#[pyclass] struct StrContainer { /* ... */ }
```

```rust
// ❌ Iterator Rust → itérable Python (pas auto)
impl Iterator for MyType { /* ... */ }

// ✅ Implémenter __iter__ et __next__
#[pymethods]
impl MyType {
    fn __iter__(slf: PyRef<'_, Self>) -> PyRef<'_, Self> { slf }
    fn __next__(&mut self) -> Option<i32> { /* ... */ }
}
```

#pagebreak()

// ── Section ───────────────────────────────────────────────────────────────
#align(center + horizon)[
  #text(size: 30pt, weight: "semibold")[5. REX : Toboggan-py]
]
#pagebreak()

// ── Slide ────────────────────────────────────────────────────────────────
= Architecture toboggan-py
```text
toboggan-core/    ← logique métier pure (no_std capable)
toboggan-client/  ← client HTTP/WebSocket Rust
toboggan-py/      ← bindings PyO3 (cdylib, abi3-py38)
   └─ src/
      ├─ lib.rs         #[pymodule]
      ├─ toboggan.rs    #[pyclass] Toboggan
      ├─ talk.rs, slides.rs, state.rs, ...
toboggan_py.pyi   ← type stubs (IDE, mypy)
```

→ #strong[Le même cœur métier], exposé en CLI, Web, Mobile, Python.

#pagebreak()

// ── Slide ────────────────────────────────────────────────────────────────
= Le `#[pyclass]`
```rust
#[pyclass]
pub struct Toboggan {
    config: TobogganConfig,
    rt: Runtime,                       // Tokio embarqué
    _ws: WebSocketClient,
    tx: UnboundedSender<Command>,      // canal vers la tâche WS
    talk: Arc<RwLock<TalkResponse>>,   // état partagé
    slides: Arc<RwLock<SlidesResponse>>,
    state: Arc<RwLock<TState>>,
}
```

Le #strong[pattern clé] :

#quote(block: true)[
#strong[Python sync, Rust async], Runtime Tokio embarqué.

]

#pagebreak()

// ── Slide ────────────────────────────────────────────────────────────────
= Les `#[pymethods]`
```rust
#[pymethods]
impl Toboggan {
    #[new]
    #[pyo3(signature = (host = "localhost", port = 8080))]
    pub fn __new__(host: &str, port: u16) -> PyResult<Self> {
        // ... setup tokio runtime, websocket, channels
    }

    #[getter]
    pub fn state(&self) -> PyResult<State> {
        let state = Arc::clone(&self.state);
        let s = self.rt.block_on(async {
            state.read().await.clone()
        });
        Ok(State(s))
    }

    pub fn next(&self) { self.send(Command::NextSlide); }
    pub fn previous(&self) { self.send(Command::PreviousSlide); }
}
```

#pagebreak()

// ── Slide ────────────────────────────────────────────────────────────────
= Côté Python
```python
from toboggan_py import Toboggan

tbg = Toboggan("localhost", 8080)

print(f"talk:  {tbg.talk}")
print(f"state: {tbg.state}")

tbg.next()           # avance d'une slide
tbg.previous()       # recule
tbg.goto(5)          # slide précise
tbg.blink()          # effet visuel
```

→ #strong[API Pythonique], #strong[moteur Rust], #strong[WebSocket temps réel]. → Cette présentation est pilotée par ce code.

#pagebreak()

// ── Section ───────────────────────────────────────────────────────────────
#align(center + horizon)[
  #text(size: 30pt, weight: "semibold")[6. Les écueils]
]
#pagebreak()

// ── Slide ────────────────────────────────────────────────────────────────
= Asynchronisme
```text
   Python (asyncio)              Rust (tokio)
 ┌─────────────────┐          ┌──────────────────┐
 │  await client   │          │  tokio::Runtime  │
 │      .fetch()   │ ─────▶   │   ┌──────────┐   │
 │                 │          │   │ reqwest  │   │
 │  ◄───── Future ─┤          │   └──────────┘   │
 │  (résolue)      │          │                  │
 └─────────────────┘          └──────────────────┘
        ↑                              ↑
        │  pyo3-async-runtimes::tokio  │
        └─────── future_into_py ───────┘
```

Deux mondes async #strong[indépendants] → il faut un pont.

#pagebreak()

// ── Slide ────────────────────────────────────────────────────────────────
= Deux patterns
```rust
// Pattern 1 : Runtime interne, API Python sync
#[pymethods]
impl Client {
    fn fetch(&self, url: &str) -> PyResult<String> {
        self.rt.block_on(async {
            reqwest::get(url).await?.text().await
        }).map_err(|e| PyRuntimeError::new_err(e.to_string()))
    }
}
```

```rust
// Pattern 2 : pyo3-async-runtimes, API Python async
#[pyfunction]
fn fetch(py: Python<'_>, url: String) -> PyResult<Bound<'_, PyAny>> {
    pyo3_async_runtimes::tokio::future_into_py(py, async move {
        reqwest::get(&url).await
            .map_err(|e| PyRuntimeError::new_err(e.to_string()))?
            .text().await
            .map_err(|e| PyRuntimeError::new_err(e.to_string()))
    })
}
```

#pagebreak()

// ── Slide ────────────────────────────────────────────────────────────────
= OpenTelemetry
```text
Python (otel-python)             Rust (opentelemetry-rust)
────────────────────             ─────────────────────────
trace_id: ABC                    trace_id: ???
span_id:  001                    span_id:  ???
   │                                 │
   │ ─── PyO3 call ──▶               │
   │                                 │   ❌ contexte perdu
   │ ◄── return ───                  │
```

Solution : injecter / extraire #strong[W3C TraceContext] aux frontières.

```text
Python : propagate.inject(carrier)
       → {"traceparent": "00-ABC-001-01"}
Rust   : Extractor reconstruit le Context
```

#pagebreak()

// ── Slide ────────────────────────────────────────────────────────────────
= Ownership : Python ou Rust ?
```text
   Python heap (gc, refcount)
 ┌─────────────────────────────┐
 │  ┌──────────┐               │
 │  │ PyObject │  refcount: 2  │
 │  └─────▲────┘               │
 │        │                    │
 └────────┼────────────────────┘
          │  Py<PyAny>  (incrémente refcount)
 ┌────────┼────────────────────┐
 │  Rust  │                    │
 │        │  struct MyClass {  │
 │        └─ obj: Py<PyAny>,   │
 │        }                    │
 └─────────────────────────────┘
```

- `Py<T>` = smart pointer Rust qui maintient une refcount Python
- GIL nécessaire pour #strong[lire/écrire] un PyObject
- ⚠️ Pas de cycle Rust ↔ Python → fuite garantie

#pagebreak()

// ── Slide ────────────────────────────────────────────────────────────────
= Le GIL et la PEP 703
Le #strong[G]lobal #strong[I]nterpreter #strong[L]ock :

- 1 thread Python à la fois exécute du bytecode
- Empêche le vrai parallélisme CPU-bound en pur Python
- Workaround : multiprocessing, ou du natif qui le relâche

#strong[#link("https://peps.python.org/pep-0703/")[PEP 703]] — Free-threaded Python (3.13+)

- Le GIL devient #strong[optionnel]
- Compile flag `--disable-gil`
- Vrai parallélisme CPU-bound

→ Les libs natives (PyO3 inclus) doivent s'adapter.

#pagebreak()

// ── Slide ────────────────────────────────────────────────────────────────
= Packaging multi-plateforme
Wheels nécessaires :

- #strong[manylinux] (glibc), #strong[musllinux] (Alpine)
- #strong[macOS] universal2 (arm64 + x86\_64)
- #strong[Windows] (x86\_64, arm64)

```yaml
# .github/workflows/release.yml
- uses: PyO3/maturin-action@v1
  with:
    target: ${{ matrix.target }}
    args: --release --out dist
    manylinux: auto
- run: maturin upload --skip-existing dist/*
```

→ `maturin-action` orchestre le cross-compile + upload PyPI.

#pagebreak()

// ── Slide ────────────────────────────────────────────────────────────────
= Tips de terrain
- 🎯 #strong[Réduire la surface FFI] — moins de franchissements = moins d'overhead
- 📦 #strong[Batcher] plutôt que appels unitaires
- ♻️ #strong[Runtime Tokio partagé] — `OnceLock<Runtime>`
- 🔓 #strong[Libérer le GIL] sur le CPU-bound — `py.allow_threads(...)`
- ✅ #strong[Tester des deux côtés] — `pytest` ET `cargo test`
- 🔍 #strong[Profiler avec #link("https://github.com/benfred/py-spy")[`py-spy`]] — voit les frames natives
- 📝 #strong[Type stubs `.pyi`] — IDE et mypy heureux

#pagebreak()

// ── Section ───────────────────────────────────────────────────────────────
#align(center + horizon)[
  #text(size: 30pt, weight: "semibold")[7. Conclusion]
]
#pagebreak()

// ── Slide ────────────────────────────────────────────────────────────────
= 4 options stratégiques
+ #strong[RIIR] — réécrire (partiellement) une lib Python en Rust pour la perf #emph[ex : pydantic-core, polars]
+ #strong[API polyglotte] — un cœur Rust, exposé partout (Python, Go, Java, …) #emph[ex : #link("https://github.com/apache/opendal")[OpenDAL], #link("https://github.com/Goldziher/kreuzberg")[Kreuzberg]]
+ #strong[Proto Python → Rust] — itérer vite, optimiser quand le besoin émerge
+ 🤔 #strong[A-t-on encore besoin de Python ?] #emph[Rust : `polars`, `axum`, `candle`, #link("https://github.com/evcxr/evcxr")[`evcxr`]]

#pagebreak()

// ── Slide ────────────────────────────────────────────────────────────────
= Pour aller plus loin
#strong[Outils]

- #link("https://pyo3.rs/")[PyO3], #link("https://www.maturin.rs/")[Maturin]
- #link("https://github.com/PyO3/pyo3-async-runtimes")[pyo3-async-runtimes], #link("https://github.com/PyO3/rust-numpy")[rust-numpy]
- #link("https://github.com/benfred/py-spy")[py-spy], #link("https://github.com/mozilla/cbindgen")[cbindgen]

#strong[Lectures]

- #link("https://ohadravid.github.io/posts/2023-03-rusty-python/")[Making Python 100x faster with Rust] — Ohad Ravid
- #link("https://pyo3.rs/latest/")[PyO3 User Guide]
- #link("https://doc.rust-lang.org/nomicon/ffi.html")[The Rustonomicon — FFI]
- #link("https://peps.python.org/pep-0703/")[PEP 703 — GIL optional]
- #link("https://astral.sh/blog")[Astral blog] — Ruff, uv

#strong[Code de la présentation]

- #link("https://github.com/ilaborie/toboggan")[github.com/ilaborie/toboggan]

#pagebreak()

